### ISSUE TITLE
Asrock rx 570 4gb will this work?

### ISSUE THREAD

**Issue by jericopulvera** [khronokernel/Catalina-GPU-Buyers-Guide#11]
https://www.asrock.com/Graphics-Card/AMD/Phantom%20Gaming%20D%20Radeon%20RX570%204G/

Will this work?

**Comment by khronokernel** [comment]
Is this an issue with the guide? Please keep the issues tab for issues with the guide, not an area for hackintosh support. 

Side note: No clue on AsRock, rarely see them so don't know their issues
