### ISSUE TITLE
5700 are supported since 15.1

### ISSUE THREAD

**Issue by rowild** [khronokernel/Catalina-GPU-Buyers-Guide#12]
According to several sources (olaila on Facebook, Morgonaut on youtube etc), the AMD 5700 graphics cards are now supported. (Just in case you'd like to update you fantastic overview, for which I am very thankful!)

**Comment by chromer030** [comment]
That's true , 5700 series working well since 10.15.1.

**Comment by rowild** [comment]
@chromer030 Do you have experience with it?

I ask, because I have to update my Hackintosh from 10.13 to 10.15 and must invest in a new Graphics card (owning a Nvidia 970 ATM, which is not supported in Catalina). I am doing some work with Blender and therefore need to balance my choice based on problems that Blender seems to have with AMD cards and Catalina support. Currently the 5700, 5700 xt, and VII are on the shortlist. What would you recommend?

**Comment by chromer030** [comment]
@rowild , I have a 5700 XT and on latest 10.15.3 and via OpenCore and WEG it is supported well , 

![dtosrzqtw5g41](https://user-images.githubusercontent.com/13361552/74218901-115b7800-4c60-11ea-8b57-7dbcbc2e21f9.png)
![yljzdvr82mf41](https://user-images.githubusercontent.com/13361552/74218970-4071e980-4c60-11ea-8bc0-6f7e4ab57cc0.jpg)

 currently i'm using it for ordinary tasks not for 3D and heavy works.
i recommend you to look at following link :

https://www.reddit.com/r/hackintosh/comments/f0qorc/mojave_to_catalina_32_gb_to_64_rx_590_to_5700_xt/

i recommend to use VII , it's fully native on macOS and much more powerful than 5700 series.
according to : https://khronokernel-3.gitbook.io/catalina-gpu-buyers-guide/modern-gpus/amd-gpu

"
Vega 20 series
Highest Supported OS: Current/Catalina

So all Vega based GPUs are natively supported in macOS with Vega 20 GPUs starting in Mojave.
While natively supported, it's recommended to still have WhateverGreen.kext installed as this helps with proper frame-buffer connections and fixes other odd issues like proper ACPI mapping and such
Supported Cards:

Radeon VII 

"

take a loot at this also :
https://github.com/acidanthera/bugtracker/issues/617

**Comment by khronokernel** [comment]
Navi support was added to the guide back in October: https://github.com/khronokernel/Catalina-GPU-Buyers-Guide/commit/b2b2119a530d213fb9d89ac5fb1c706194524fff

**Comment by rowild** [comment]
@khronokernel I thought I saw the 5700 listed under "unsupported card" somewhere, but can't find the place now. I will report back with proper information, if I find it again, otherwise please excuse the needless issue! However, thanks for responding!

@chromer030 Thank you so much for your most valuable feedback! Highly appreciated!!!
