### ISSUE TITLE
Radeon Pro WX 3100 has a Lexa core

### ISSUE THREAD

**Issue by agoodney** [khronokernel/Catalina-GPU-Buyers-Guide#3]
I recently purchased a Radeon Pro WX 3100 which doesn't work in Mojave. Further research shows that it has a Lexa core. This page seems to confirm that fact:

https://techgage.com/article/amd-radeon-pro-wx-3100-workstation-graphics-card-review/

Best I can tell the Lexa cores are not supported (as stated in the guide)

**Comment by khronokernel** [comment]
Apologies on the delayed response, only just saw the issue. Thank you for pointing that out will be fixed shortly!
