### ISSUE TITLE
Maybe issue of GK106 fixed on Mojave about 8 month ago.

### ISSUE THREAD

**Issue by mifjpn** [khronokernel/Catalina-GPU-Buyers-Guide#4]
First I think your information collection ability is very wonderful!!
This issue is old.So I think that is not so important.

The issue of GK106 was buggy-mortion like the following Web ...
https://www.insanelymac.com/forum/topic/339309-graphic-problem-zotac-geforce-650-ti-boost-2gb-with-mojave/

But the issue was fixed and GK106 seems to be natively supported.
https://www.reddit.com/r/hackintosh/comments/ag17d9/any_success_with_gtx_650_ti/ee2zia7/

And I tested Geforce 650Ti on i7-3770K,B75M-PLUS. It's work correctly.
https://translate.weblio.jp/web/english?lp=JE&url=https%3A%2F%2Fhacnohulot.exblog.jp%2F29682803%2F&sentenceStyle=spoken
(Sorry my webpage is japanese.)

I think that you should suggest that GK106 may work(at least) in the text.

Thank you for reading this text.

**Comment by khronokernel** [comment]
I apologize but I just recently dealt with GK106 issues on the AMD OS X server, the issues haven't gone away even in 10.14.6. Unless you're able to find out which release that these changes were implemented I cannot approve such cards, same reason I refuse to recommend XFX and PowerColour even though it is possible to get them to work. Catalina also didn't have any major changes to the NVDAGK100Hal.kext and I don't want to reverse engineer the kext again just to see if the memory leaks were fixed unless you can provide a reliable source, users are still banging their heads here over the situation: [GTX 660 glitch issue](https://www.tonymacx86.com/threads/gtx-660-glitch-issue-with-macos-high-sierra-10-13.233101/)

I appreciate the help though!
