### ISSUE TITLE
WX 2100 is listed as supported device

### ISSUE THREAD

**Issue by Dresel** [khronokernel/Catalina-GPU-Buyers-Guide#5]
Hi,

WX 2100 is listed as supported device, in fact it's running a lexa core (like wx 3100) and should be moved to unsupported device section?

**Comment by khronokernel** [comment]
Oh completely missed that, thanks! [Change pushed](https://github.com/khronokernel/Catalina-GPU-Buyers-Guide/commit/37122c5796c302b27f8a7244833bfa465eca8428)
