### ISSUE TITLE
Quadro K2000 and Wx4100

### ISSUE THREAD

**Issue by rpzrpzrpz** [khronokernel/Catalina-GPU-Buyers-Guide#6]
In your Mojave Guide, you did not list Nvidia Quadro K2000 as supported, but in Catalina, you mention Nvidia Quadro k2000 (Kepler) support.  Why is there a difference?

I had a lot of trouble getting Mojave 10.14.4 installed with AORUS Gigabyte Z390 and i3-8100 and Quadro K2000 working well, especially with dual monitor.  Ultimately, I punted and am currently running iGPU UHD 630.  (Quadro K2000 runs fine under Windows 10 on same MOBO)

Now, my AORUS BIOS keeps resetting every 3 days and I think the MOBO is going to die soon.  Looking at a Asus ROG Strix Z390-I to replace the short-lived AORUS Gigabyte Z390 MiniITX.  

Should I get an AMD Radeon Wx4100 to install into the Asus Z390 MiniITX or should I just try the Quadro K2000 again for Catalina?

Which is more naturally supported, Wx4100 or K2000?

**Comment by khronokernel** [comment]
Hello, so to answer some questions:
* I no longer support the Mojave guide, I'd rather people go for the newer guide
* Remaking the guide showed the I was missing some GPUs so I added the K2000 and some other GK 107 cards, it is supported as shown [here](https://www.techpowerup.com/gpu-specs/quadro-k2000.c1838)
* Wx4100 is natively supported and much newer, so I would advise going for that if possible as it's closer to the MacPro7,1's RP580x so better long term support
