### ISSUE TITLE
AMD Cards / Navi note question

### ISSUE THREAD

**Issue by klebba** [khronokernel/Catalina-GPU-Buyers-Guide#8]
Hi there — thanks for the great guide. I'm reading through this section and have a question: https://github.com/khronokernel/Catalina-GPU-Buyers-Guide/blame/master/amd-gpu.md#L17

Specifically this part: `keep in mind DisplayPort can be a hit or miss as WhateverGreen needs to be adapted.`

What does this mean? Can you please elaborate a bit?

Thank you!

**Comment by khronokernel** [comment]
Hello, regarding the comment its related to [this bug report thread for WhateverGreen](https://github.com/acidanthera/bugtracker/issues/617). Specifically this comment:

> For my reference PCB based card (blower cooler), the default connector order from BIOS/UEFI time is from bottom (PCI-E connector) to top, or DP/HDMI/DP/DP ports. On macOS, however, the preferred connector order is reversed, using top to bottom (PCI-E connector), or DP/DP/HDMI/DP ports.

Though from the sounds of it on AppleLife, Acidanthera is preferring to wait and see if Apple fixes it. Hopefully this clears up some confusion, I'll add the link to the guide for further users
