### ISSUE TITLE
No DRM with IGPU only

### ISSUE THREAD

**Issue by Sn0wStorm** [khronokernel/Catalina-GPU-Buyers-Guide#9]
Could you please add the information that with using igpu alone (as of Haswell?) you will not be able to get DRM working in osx.

That means no iTunes Movies, TV+, Sidecar, and Netflix/Prime only in Chrome.

See here:
https://github.com/acidanthera/WhateverGreen/commit/7d30dd8a624d0d3b2d4882fcc689b9db4964efd5#r36078372
https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.Chart.md
https://www.tonymacx86.com/threads/an-idiots-guide-to-lilu-and-its-plug-ins.260063/#DRM-IGPU

**Comment by khronokernel** [comment]
Oh that's a great idea, thank you and appreciate you also giving me some links. Saves me some time. Expect a commit in a couple hours

**Comment by khronokernel** [comment]
Just fixed in latest commit: [eb7871d](https://github.com/khronokernel/Catalina-GPU-Buyers-Guide/commit/d371678100cb8d87a9295cfad3fc3e3a473874e8)
